<a href="https://colab.research.google.com/github/HarshNVyas/ML-Projects/blob/main/Models%20from%20Scratch/Na%C3%AFve_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mount Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Importing Libraries

In [ ]:
import numpy as np
import pandas as pd

# Importing Data

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab/Datasets/Weather.csv')
df

Outlook Play
0      Rainy    Y
1      Sunny    Y
2   Overcast    Y
3   Overcast    Y
4      Sunny    N
5      Rainy    Y
6      Sunny    Y
7   Overcast    Y
8      Rainy    N
9      Sunny    N
10     Sunny    Y
11     Rainy    N
12  Overcast    Y
13  Overcast    Y

In [ ]:
# Prints number of Rows in a dataframe
length = len(df.index)
print(length)

14


In [ ]:
arr = np.zeros((4,3),dtype = 'float')
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
for i in range (length):
    if df.loc[i,'Outlook'] == 'Overcast' and df.loc[i,'Play'] == 'Y':
        arr[0,0] += 1
    elif df.loc[i,'Outlook'] == 'Overcast' and df.loc[i,'Play'] == 'N':
        arr[0,1] += 1
    elif df.loc[i,'Outlook'] == 'Rainy' and df.loc[i,'Play'] == 'Y':
        arr[1,0] += 1
    elif df.loc[i,'Outlook'] == 'Rainy' and df.loc[i,'Play'] == 'N':
        arr[1,1] += 1
    elif df.loc[i,'Outlook'] == 'Sunny' and df.loc[i,'Play'] == 'Y':
        arr[2,0] += 1
    elif df.loc[i,'Outlook'] == 'Sunny' and df.loc[i,'Play'] == 'N':
        arr[2,1] += 1
    else:
            print('Incorrect Dataset for [ '+w_type+' , '+YoN+' ]')

arr

array([[10.        ,  0.        ,  0.35714286],
       [ 4.        ,  4.        ,  0.28571429],
       [ 6.        ,  4.        ,  0.35714286],
       [ 0.71428571,  0.28571429,  0.        ]])

In [ ]:
arr[0,2] = (arr[0,0] + arr[0,1])/length
arr[1,2] = (arr[1,0] + arr[1,1])/length
arr[2,2] = (arr[2,0] + arr[2,1])/length
arr[3,0] = (arr[1,0]+arr[2,0]+arr[0,0])/length
arr[3,1] = (arr[1,1]+arr[2,1]+arr[0,1])/length
#arr[4,2] = (arr[1,2]+arr[2,2]+arr[3,2])/length
arr

array([[10.        ,  0.        ,  0.71428571],
       [ 4.        ,  4.        ,  0.57142857],
       [ 6.        ,  4.        ,  0.71428571],
       [ 1.42857143,  0.57142857,  0.        ]])

# Output

In [ ]:
total_yes = arr[1,0]+arr[2,0]+arr[0,0]
total_no = arr[1,1]+arr[2,1]+arr[0,1]
p_yes = arr[3,0]
p_no = arr[3,1]
p_over = arr[0,2]
p_rainy = arr[1,2]
p_sunny = arr[2,2]
p_o_y = (arr[0,0])/total_yes
p_o_n = (arr[0,1])/total_no
p_r_y = (arr[1,0])/total_yes
p_r_n = (arr[1,1])/total_no
p_s_y = (arr[2,0])/total_yes
p_s_n = (arr[2,1])/total_no
pred_over_yes = p_o_y*p_yes/p_over
pred_over_no = p_o_n*p_no/p_over
pred_rainy_yes = p_r_y*p_yes/p_rainy
pred_rainy_no = p_r_n*p_no/p_rainy
pred_sunny_yes = p_s_y*p_yes/p_sunny
pred_sunny_no = p_s_n*p_no/p_sunny
print('p_o_y -> ',p_o_y,' and p_o_n - > ',p_o_n)
print('pred_o_y -> ',pred_over_yes,' and pred_o_n - > ',pred_over_no)

print('This program predicts wheather you can play or not in a weaher you input,\n')
inp = input('Enter:\n1.Overcast\n2.Rainy\n3.Sunny\ninput : ')

if inp == 'Sunny':
    if(pred_sunny_yes > pred_sunny_no):
        print('You can go to play out!!')
    else:
        print('Stay home!!')
elif inp == 'Rainy':
    if(pred_rainy_yes > pred_rainy_no):
        print('You can go to play out!!')
    else:
        print('Stay home!!')
elif inp == 'Overcast':
    if(pred_over_yes > pred_over_no):
        print('You can go to play out!!')
    else:
        print('Stay home!!')
else:
    print('Invalid Input:')

p_o_y ->  0.5  and p_o_n - >  0.0
pred_o_y ->  1.0  and pred_o_n - >  0.0
This program predicts wheather you can play or not in a weaher you input,

Enter:
1.Overcast
2.Rainy
3.Sunny
input : Overcast
You can go to play out!!
